image: python:3.6

before_script:
  - pip install -r requirements-test.txt
stages:
  - test_and_style
  - type # this is BETA
  - linting # latest stage because this is BETA, and just a plus for student

check_pep8:
  stage: test_and_style
  script:
    - cd /builds/pyfml/pyfml && make style

type:
  stage: type
  script:
    - cd /builds/pyfml/pyfml && make type || true

unittest:
  stage: test_and_style
  script:
    - cd /builds/pyfml/pyfml && make test

pylint:
  stage: linting
  script:
    - cd /builds/pyfml/pyfml && make lint

security_check:
  stage: linting
  script:
    - cd /builds/pyfml/pyfml && make sec || true
